version: '3'

services:
  # Service PostgreSQL
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appdaf_network

  # Service de l'application
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      dsn: pgsql:host=postgres;port=5432;dbname=${DB_DATABASE};
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      URL: ${URL}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_TOKEN: ${TWILIO_TOKEN}
      TWILIO_FROM: ${TWILIO_FROM}
      IMG_DIR: ${IMG_DIR}
    ports:
      - "10000:80"
    volumes:
      - app_uploads:/var/www/html/public/uploads
    networks:
      - appdaf_network

networks:
  appdaf_network:
    driver: bridge

volumes:
  postgres_data:
  app_uploads: